version: '3'

services:
  db:
    image: 'bitnami/postgresql:latest'
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sb1234@
      - POSTGRES_DB=sampledb
  config-service:
    image: 'pixie-config-server:latest'
    build: './pixie-config-server/.'
    container_name: 'pixie-config-server'
    ports:
      - "8088:8088"
    networks:
      - core-network
    environment:
      - "SPRING_PROFILES_ACTIVE=native,production"
      - "BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"

    logging:
      options:
        max-size: "10000m"
        max-file: "1000"

  admin-service:
    image: 'pixie-admin-server:latest'
    build: './pixie-admin-server/.'
    container_name: 'pixie-admin-server'
    depends_on:
      - config-service
    ports:
      - "8087:8087"
    networks:
      - core-network
    environment:
      - "SPRING_PROFILES_ACTIVE=native,production"
      - "BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"
    logging:
      options:
        max-size: "10000m"
        max-file: "1000"

  discovery-service:
    image: 'pixie-discovery-server'
    build: './pixie-discovery-server/.'
    container_name: 'pixie-discovery-service'
    depends_on:
      - config-service
      - admin-service
    ports:
      - "8061:8061"
    networks:
      - core-network
    environment:
      - "SPRING_PROFILES_ACTIVE=native,production"
    logging:
      options:
        max-size: "10000m"
        max-file: "1000"


  gateway-service:
    image: 'pixie-gateway-server'
    build: './pixie-gateway-server/.'
    container_name: 'pixie-gateway-server'
    depends_on:
      - config-service
      - admin-service
      - discovery-service
    ports:
      - "8060:8060"
    networks:
      - core-network
    environment:
      - "SPRING_PROFILES_ACTIVE=native,production"
      - "BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"
    logging:
      options:
        max-size: "10000m"
        max-file: "1000"




#  person-service:
#    image: 'pixie-person-service'
#    build: './pixie-person-service/.'
#    container_name: 'pixie-person-service'
#    depends_on:
#      - config-service
#      - admin-service
#      - discovery-service
#      - gateway-service
#    networks:
#      - core-network
#    environment:
#      - "SPRING_PROFILES_ACTIVE=native,production"
#      - "BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"
#    logging:
#      options:
#        max-size: "10000m"
#        max-file: "1000"

  # document-service:
  #   image: 'pixie-document-service'
  #   build: './pixie-document-service/.'
  #   container_name: 'pixie-document-service'
  #   depends_on:
  #     - config-service
  #     - admin-service
  #     - discovery-service
  #     - gateway-service
  #   networks:
  #     - core-network
  #   environment:
  #     - "SPRING_PROFILES_ACTIVE=native,production"
  #     - "BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"
  #   logging:
  #     options:
  #       max-size: "10000m"
  #       max-file: "1000"

  # note-service:
  #   image: 'pixie-note-service'
  #   build: './pixie-note-service/.'
  #   container_name: 'pixie-note-service'
  #   depends_on:
  #     - config-service
  #     - admin-service
  #     - discovery-service
  #     - gateway-service
  #   networks:
  #     - core-network
  #   environment:
  #     - "SPRING_PROFILES_ACTIVE=native,production"
  #     - "BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"
  #   logging:
  #     options:
  #       max-size: "10000m"
  #       max-file: "1000"


  # notification-service:
  #   image: 'pixie-notification-service'
  #   build: './pixie-notification-service/.'
  #   container_name: 'pixie-notification-service'
  #   depends_on:
  #     - config-service
  #     - admin-service
  #     - discovery-service
  #     - gateway-service
  #   networks:
  #     - core-network
  #   environment:
  #     - "SPRING_PROFILES_ACTIVE=native,production"
  #     - "BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"
  #   logging:
  #     options:
  #       max-size: "10000m"
  #       max-file: "1000"


  # reminder-service:
  #   image: 'pixie-reminder-service'
  #   build: './pixie-reminder-service/.'
  #   container_name: 'pixie-reminder-service'
  #   depends_on:
  #     - config-service
  #     - admin-service
  #     - discovery-service
  #     - gateway-service
  #   networks:
  #     - core-network
  #   environment:
  #     - "SPRING_PROFILES_ACTIVE=native,production"
  #     - "BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"
  #   logging:
  #     options:
  #       max-size: "10000m"
  #       max-file: "1000"


  # task-service:
  #   image: 'pixie-task-service'
  #   build: './pixie-task-service/.'
  #   container_name: 'pixie-task-service'
  #   depends_on:
  #     - config-service
  #     - admin-service
  #     - discovery-service
  #     - gateway-service
  #   networks:
  #     - core-network
  #   environment:
  #     - "SPRING_PROFILES_ACTIVE=native,production"
  #     - "BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"
  #   logging:
  #     options:
  #       max-size: "10000m"
  #       max-file: "1000"

volumes:
  pgdata:

networks:
  core-network:
